[package]
name = "mjolnir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.5.0"
rand = "0.8.5"
openssl = "0.10.38"
hex = "0.4.3"
owo-colors = "3.2.0"
regex = "1"
